name: Terraform AWS DynamoDB  Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - "*/**"
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  terraform:
    name: ${{matrix.runner}} - ${{ matrix.environment }}
    runs-on: ${{ matrix.runner }}
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: prod
            runner: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve